[target.aarch64-linux-android]
ar = "llvm-ar"
linker = "aarch64-linux-android21-clang"
rustflags = [
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog",
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"
