name: 🏗️ Build For Windows
on:
  workflow_call:
jobs:
  build-windows:
    name: 🪟 Build Windows For ${{ matrix.target }}
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]
    steps:
      - name: 🔍 Checkout Code
        uses: actions/checkout@v6
      - name: ⚙️ Set Up Rust for ${{ matrix.target }}
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
          components: rustfmt, clippy
      - name: 🛠️ Build Release EXE
        shell: pwsh
        run: cargo build --target ${{ matrix.target }} --release
      - name: 📦 Package Artifacts (zip)
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "target/${{ matrix.target }}/release/getquotes.exe", "man/getquotes.ps1xml", "LICENSE", "completions/", "config.schema.json"`
            -DestinationPath "getquotes-${{ matrix.target }}.zip"
      - name: 🚢 Upload Windows Artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-${{ matrix.target }}
          path: getquotes-${{ matrix.target }}.zip
